#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.

#  - Указать настройки подключения к базе данных.
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/bankcards
    username: postgres
    password: 2133
    driver-class-name: org.postgresql.Driver

  application:
    name: bankcards

  jpa:
    hibernate:
#      ddl-auto: none
      ddl-auto: create
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

#  - Указать порт приложения.
server:
  port: 8088

#  - Настроить параметры безопасности и JWT.
security:
  jwt:
    secret-key: k3R8nh9sZ7v5wWmQ2xP1aB6cD4eF7gH0iJ9kL3mN5oQ= # Секретный ключ для подписи JWT
    issuer: check-app # Издатель токена
    access-token-expire-time: 3600000   # Время жизни access токена (в миллисекундах, указан 1 час)
    refresh-token-expire-time: 86400000 # Время жизни refresh токена (в миллисекундах, указано 24 часа)

##  - Включить Swagger UI.

# Настройка Swagger (OpenAPI)
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.example.bankcards.controller
#  default-produces-media-type: application/json
#  default-consumes-media-type: application/json

# Настройка логирования
logging:
  level:
    root: INFO
    com.example.bankcards: DEBUG # Логи приложения
    org.springframework.web: DEBUG # HTTP запросы (DispatcherServlet)
    org.springframework.security: DEBUG # Аутентификация и авторизация
    org.hibernate.SQL: DEBUG # SQL-запросы
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # Привязка параметров
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log
    max-size: 10MB # Максимальный размер файла
    max-history: 7 # Количество хранимых файлов
